version: '3.8'

services:
  neo4j:
    image: neo4j:5.24.2-community
    container_name: neo4j-data-hw1
    restart: always
    ports:
      - "7474:7474"  # HTTP browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/your_password
      - NEO4JLABS_PLUGINS=["apoc", "bloom"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,bloom.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
      - NEO4J_dbms_memory_pagecache_size=512M
      - server.config.strict_validation.enabled=false

  rdbms:
    image: postgres:17-alpine
    container_name: hw1-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: data-hw1
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nosql:
    image: mongo:5.0.3
    container_name: hw1-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping")' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  datawarehouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_dw
    restart: always
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native TCP interface
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=your_password
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_db
    restart: always
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init_mssql.sql:/docker-entrypoint-initdb.d/init_mssql.sql
    command: /bin/bash -c "sleep 30 && /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -i /docker-entrypoint-initdb.d/init_mssql.sql && tail -f /dev/null"

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  pg_data:
  mongo_data:
  clickhouse_data:
  mssql_data:
